version: '3.8'
services:
  postgres:
    container_name: frimpong
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nath
      POSTGRES_DB: Pearl
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: frimpongyeboah0@gnail.com
      PGADMIN_DEFAULT_PASSWORD: Asante
    restart: unless-stopped

volumes:
  postgres-data: